name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '**' ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    uses: 9506hqwy/actions/.github/workflows/dotnet-ci.yml@main
    with:
      # because HTML format is 5 GiB over.
      html-report-format: HtmlSummary
